version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-backend
    ports:
      - "${PORT}:3030"
    environment:
      BD_HOST: ${DB_HOST}
      BD_USER: ${DB_USER}
      BD_PASSWORD: ${DB_PASSWORD}
    networks:
      - test-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql-db
    restart: always
    stdin_open: true
    tty: true
    command: /bin/bash

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_ADMIN_USER}
      PMA_PASSWORD: ${DB_ADMIN_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - test-network

volumes:
  mysql_data:

networks:
  test-network:
    name: test-network
    driver: bridge